language: node_js
node_js:
- '12'
script:
- yarn build
deploy:
  api_key:
    secure: Dv93IKjqt95FbPeZo5F/yNYaFxwr1/VLCCDFayS6oCpGB+nw54Uf8uPc3IBakEvPh6YVvma7m8ukMoTQmJAnXTkkOx3rhskLEfQoc8uu6NIGoCnvVEBXFtIUAEI4bvCZLSCczNI61keC43yAPT/Qfq2d6jThECbTpLJzm17/9SA93yJb9gn0AoUY3voWB9CrY8oV8xAgDJJwgnn3ko7UgADJ+FiD5mJuGJM7wbu/b6F2lmEtHe1IgUN1HFgjMOnRHN54coJv7ytf04sg8LSjOS+9k73FIYBbc2ZS4AgKT3uGy3ELQr9Aa6V3QMzbcH1w/5XcTFY5swETcAc2VTEjZH7k4sqgZfh6eGBqeXZeXpU2TNIPR67/+MaQ+c0/pH9+SdBZXp2wsRSgI+KcRGkyvFtFBf6RDZHWseYoCvBciYq4Y2DhctpH9OMLnojcgChfWe8+hkOkuKCwxZ9tGbqm3WZjXbAy2OKQfdfwEqGzGoBdn18+X5fS8oMVClLTCQL5r9mBDWW+7k3LggUTrXwpZeirJWuIKjS0MGAM0AchWJAuhoW/sKH8dnERj67efJghBYVvD9WLpY8ngST0wWXC/+c3ZN75scmavDBwT22SX+X2VyjUEKd1KbdIl85E7XE9pnpSLwZo9xqSYAawqi4A+k5OWei6UCH16PoDeRLQwpU=
